version: "3.1"

services:
    database:
      mem_limit: 2048m
      image: mariadb:latest
      restart: unless-stopped
      ports:
        - 3306:3306
      env_file: .env
      environment:
        MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
        MYSQL_DATABASE: '${MYSQL_DATABASE}'
        MYSQL_USER: '${MYSQL_USER}'
        MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      volumes:
        - db-data:/var/lib/mysql
      networks:
        - wordpress-network


    phpmyadmin:
      depends_on:
        - database
      image: phpmyadmin:latest
      restart: unless-stopped
      ports:
        - 8081:80
      env_file: .env
      environment:
        PMA_HOST: database
        MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      networks:
        - wordpress-network

    wordpress:
      depends_on:
        - database
        - redis
      build:
        context: .
        dockerfile: ./Dockerfile
          #ports:
        #- "8080:80"
          #image: Dockerfile
      restart: unless-stopped
      env_file: .env
      environment:
        WORDPRESS_DB_HOST: database:3306
        WORDPRESS_DB_NAME: '${MYSQL_DATABASE}'
        WORDPRESS_DB_USER: '${MYSQL_USER}'
        WORDPRESS_DB_PASSWORD: '${MYSQL_PASSWORD}'
        WP_REDIS_HOST: '${WP_REDIS_HOST}'
        WP_REDIS_PORT: '${WP_REDIS_PORT}'
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.wordpress.rule=Host(`avap.local`)" ## && PathPrefix(`/wp`)"
        - "traefik.http.routers.wordpress.entrypoints=web"
        - "traefik.http.routers.wordpress.tls=true"
          ##- "traefik.http.routers.wordpress.tls.certresolver=myresolver" # Replace with your certificate resolver name
        - "traefik.http.services.wordpress.loadbalancer.server.port=80" # WordPress usually listens on port 80
      volumes:
        - ./:/var/www/html
      networks:
        - wordpress-network
        - proxy
    redis:
      image: redis:latest
      expose:
        - 6379
      restart: unless-stopped
      volumes:
        - redis_data:/data
      networks:
        - wordpress-network

    mailpit:
      image: axllent/mailpit
      container_name: mailpit
      restart: unless-stopped
      volumes:
         - mailpit-data:/data
      ports:
        - 8025:8025
        - 1025:1025
      environment:
        MP_MAX_MESSAGES: 5000
        MP_DATABASE: /data/mailpit.db
        MP_SMTP_AUTH_ACCEPT_ANY: 1
        MP_SMTP_AUTH_ALLOW_INSECURE: 1
      networks:
        - wordpress-network

    traefik:
      image: "traefik:v3.4"
      container_name: "traefik"
      restart: unless-stopped
      security_opt:
        - no-new-privileges:true
      networks:
        - proxy
        - wordpress-network   
      command:
        - "--api.insecure=true"
        - "--api.dashboard=true"
        - "--providers.docker=true"
        - "--providers.docker.exposedbydefault=false"
        - "--providers.docker.network=proxy"
        - "--entryPoints.web.address=:80"
      ports:
        - "80:80"
        - "8080:8080"
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  db-data:
  redis_data:
  mailpit-data:

networks:
  proxy:
    name: proxy
  wordpress-network:
    driver: bridge
